### PR TITLE
Proactively grab customer ID during initialization, bump Radar to 1.3.0 to allow anonymous tracking

### PR DESCRIPTION
**Pull request by nickpatrick**
TODO: Can we proactively get customer ID and call `[Radar setUserId:customerId]` on initialization and on alias changes?

### CODE REVIEW

**Comment by nickpatrick** [comment]
I made the change to proactively grab customer ID. Looks like the Leanplum kit already does the same.

**Comment by nickpatrick** [comment]
Hey @peterjenkins and @samdozor, this is tested and ready to go if it looks good to you. All this does is bump Radar SDK to version 1.3 and proactively grab customer ID during initialization like the Leanplum kit. There are no breaking changes in 1.3. The major difference in 1.3 is that anonymous users (without a customer ID) can now be tracked in Radar, end-to-end from the kit through the feed.

**Comment by nickpatrick** [comment]
Looks like the base mP version was just updated. I merged in those changes, let me know if you see any issues.

**Comment by nickpatrick** [comment]
Hey @samdozor, realizing that there are breaking changes in 7.x. If there's any way we could release a version of the kit that depends on 6.x so customers can upgrade with no code changes, that would be amazing.

**Comment by nickpatrick** [comment]
I just resolved merge conflicts with the `radar-hotfix` branch to that end.

**Comment by samdozor** [comment]
Superseded by https://github.com/mparticle-integrations/mparticle-apple-integration-radar/pull/6

**Pull request closed without merging**
